image: node:6.10.2
pipelines:
  branches:
    master:
      - step:
          script:
            - npm install
            - npm run style
            - sh ./bashscripts/setdb.sh "staging" $DB_STAGING
            - sh ./bashscripts/deploy.sh "prod"
    develop:
      - step:
          script:
            - npm install
            - npm run style
            - sh ./bashscripts/setdb.sh "staging" $DB_STAGING
            - sh ./bashscripts/deploy.sh "staging"
