image: node:6.10.2
pipelines:
  branches:
    master:
      - step:
          script:
            - npm install
            - npm run style
            - echo 'Deploying to PRODUCTION environment...'
            - sh ./bashscripts/deploy.sh "prod"
    develop:
      - step:
          script:
            - npm install
            - npm run style
            - echo 'Deploying to STAGING environment...'
            - sh ./bashscripts/deploy.sh "staging"
