image: node:6.10.2
pipelines:
  branches:
    master:
      - step:
          script:
            - sh ./bashscripts/pipeline.sh "prod" $DB_PROD
    develop:
      - step:
          script:
            - sh ./bashscripts/pipeline.sh "staging" $DB_STAGING
