service: prototype-app

frameworkVersion: "=1.11.0"

provider:
  name: aws
  profile: awsdev
  region: eu-west-1
  stage: dev
  runtime: nodejs6.10
  memorySize: 128
  timeout: 6
  apiKeys:
    - ${opt:stage}-devkey

custom:
  apiversion: v1

functions:
  probeGetHealth:
    handler: functions/probe/probehandler.getHealth
    description: Check health status
    events:
      - http:
          method: get
          path: ${self:custom.apiversion}/probe/health
          private: true
