service: prototype-app
frameworkVersion: "=1.11.0"

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-west-1
  profile: awsdev

functions:
  probeGetHealth:
    handler: functions/probe/probehandler.getHealth
    name: getHealth
    description: Check health status
    runtime: nodejs6.10
    memorySize: 128
    timeout: 6
    events:
      - http:
          method: get
          path: probe/health
